
package com.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import bean.TodoList;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyFirstService", targetNamespace = "http://www.service.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyFirstService {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.service.TodoList>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryItem", targetNamespace = "http://www.service.com", className = "com.service.QueryItem")
    @ResponseWrapper(localName = "queryItemResponse", targetNamespace = "http://www.service.com", className = "com.service.QueryItemResponse")
    @Action(input = "http://www.service.com/MyFirstService/queryItemRequest", output = "http://www.service.com/MyFirstService/queryItemResponse")
    public List<com.service.TodoList> queryItem(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        XMLGregorianCalendar arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        XMLGregorianCalendar arg2);

    /**
     * 
     * @param item
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addItem", targetNamespace = "http://www.service.com", className = "com.service.AddItem")
    @ResponseWrapper(localName = "addItemResponse", targetNamespace = "http://www.service.com", className = "com.service.AddItemResponse")
    @Action(input = "http://www.service.com/MyFirstService/addItemRequest", output = "http://www.service.com/MyFirstService/addItemResponse")
    public boolean addItem(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        com.service.TodoList item);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "userRegister", targetNamespace = "http://www.service.com", className = "com.service.UserRegister")
    @ResponseWrapper(localName = "userRegisterResponse", targetNamespace = "http://www.service.com", className = "com.service.UserRegisterResponse")
    @Action(input = "http://www.service.com/MyFirstService/userRegisterRequest", output = "http://www.service.com/MyFirstService/userRegisterResponse")
    public boolean userRegister(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteItem", targetNamespace = "http://www.service.com", className = "com.service.DeleteItem")
    @ResponseWrapper(localName = "deleteItemResponse", targetNamespace = "http://www.service.com", className = "com.service.DeleteItemResponse")
    @Action(input = "http://www.service.com/MyFirstService/deleteItemRequest", output = "http://www.service.com/MyFirstService/deleteItemResponse")
    public boolean deleteItem(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "clearItem", targetNamespace = "http://www.service.com", className = "com.service.ClearItem")
    @ResponseWrapper(localName = "clearItemResponse", targetNamespace = "http://www.service.com", className = "com.service.ClearItemResponse")
    @Action(input = "http://www.service.com/MyFirstService/clearItemRequest", output = "http://www.service.com/MyFirstService/clearItemResponse")
    public boolean clearItem(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
